module.exports = [
  {
    name: 'isy-eslint/test',
    files: ['**/*.spec.ts', '**/*.test.ts'],
    rules: {
        '@stylistic/brace-style': ['error'],
        '@stylistic/comma-dangle': ['error'],
        '@stylistic/comma-spacing': ['error'],
        '@stylistic/function-call-spacing': ['error'],
        '@stylistic/keyword-spacing': ['error'],
        '@stylistic/quotes': ['error', 'single'],
        '@stylistic/semi': ['error', 'always'],
        '@stylistic/indent': ['error', 2, { 'SwitchCase': 1 }],
        '@typescript-eslint/ban-ts-comment': 'error',
        '@typescript-eslint/only-throw-error': ['error'],
        '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
        '@typescript-eslint/default-param-last': ['error'],
        '@typescript-eslint/dot-notation': ['error'],
        '@typescript-eslint/explicit-function-return-type': ['error'],
        '@typescript-eslint/explicit-member-accessibility': [
        'error',
        {
            'accessibility': 'no-public'
        }
        ],
        '@typescript-eslint/no-dupe-class-members': ['error'],
        '@typescript-eslint/no-loop-func': ['error'],
        '@typescript-eslint/no-redeclare': ['error'],
        '@typescript-eslint/no-unnecessary-boolean-literal-compare': ['error'],
        '@typescript-eslint/no-unnecessary-qualifier': ['error'],
        '@typescript-eslint/no-unnecessary-type-arguments': ['error'],
        '@typescript-eslint/no-unused-expressions': ['error'],
        '@typescript-eslint/no-unused-vars': 'off',
        '@typescript-eslint/no-use-before-define': ['error'],
        '@typescript-eslint/no-useless-constructor': ['error'],
        '@typescript-eslint/prefer-for-of': ['error'],
        '@typescript-eslint/prefer-includes': ['error'],
        '@typescript-eslint/prefer-literal-enum-member': ['error'],
        '@typescript-eslint/prefer-nullish-coalescing': ['error'],
        '@typescript-eslint/prefer-optional-chain': ['error'],
        '@typescript-eslint/prefer-reduce-type-parameter': ['error'],
        '@typescript-eslint/prefer-string-starts-ends-with': ['error'],
        '@typescript-eslint/promise-function-async': ['error'],
        '@typescript-eslint/return-await': ['error'],
        'default-param-last': 'off',
        'dot-notation': 'off',
        'no-dupe-class-members': 'off',
        'no-loop-func': 'off',
        'no-loss-of-precision': 'error',
        'no-redeclare': 'off',
        'no-return-await': 'off',
        'no-unused-expressions': 'off',
        'no-unused-vars': 'off',
        'no-use-before-define': 'off',
        'no-useless-constructor': 'off',
        'space-before-function-paren': 'off',
        '@typescript-eslint/no-magic-numbers': ['off'],
        '@typescript-eslint/no-unsafe-assignment': ['off'],
        '@typescript-eslint/no-unsafe-member-access': ['off'],
        '@typescript-eslint/no-unsafe-argument': ['off'],
        '@typescript-eslint/no-unsafe-call': ['off'],
        '@typescript-eslint/no-unsafe-return': ['off'],
        '@typescript-eslint/unbound-method': ['off']
    }
  }
];